### ISSUE TITLE
Branch changing case sensitive

### ISSUE THREAD

**Issue by ivanbanov** [tzkhan/pr-update-action#1]
Hey I have the following config
```
on:
  pull_request:
    types: [opened]

name: Set JIRA ticket
jobs:
  update_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: tzkhan/pr-update-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          branch-regex: '[A-Z]+-[0-9]+|no-ticket'
          lowercase-branch: false
          title-template: '[%branch%] '
          uppercase-title: false
          body-template: "### JIRA: [%branch%](https://company-xyz.atlassian.net/browse/%branch%)"
          uppercase-body: false
```

the expected behavior is
branches using `no-ticket` such as `feat/no-ticket/foo` should have the title
```
[no-ticket] Description foo
```
and for branch using `feat/QUX-123/bar` should have the title
```
[QUX-123] Description bar
```

but it's not working at all, the `no-ticket` case is always using uppercase
and regular expression for the `QUX-123` only works if I consider lowercase `[a-z]+-[0-9]+|no-ticket`

is it actually a bug?
