### ISSUE TITLE
Don't fail the action if the branch name doesn't match?

### ISSUE THREAD

**Issue by benrowe-chuffed** [tzkhan/pr-update-action#33]
Thanks for your GH action.

It would be nice if there was an option to not fail the step if the branch name does not match.

**Comment by jfeldstein-cw** [comment]
Use the native `branches:` filter so it only runs on a given branch pattern

eg: 

```
# .github/workflows/action.yml
on:
  pull_request:
    types:
      - opened
    branches:
      - main
```

**Comment by eddielin0926** [comment]
You can use [`continue-on-error`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error) to prevents a job from failing when a step fails.

```yaml
- uses: tzkhan/pr-update-action@v2
  continue-on-error: true
  with:
    repo-token: "${{ secrets.GITHUB_TOKEN }}"
    head-branch-regex: 'foo-\d+'
    title-template: '[%headbranch%] '
```
